
CREATE TABLE CUSTOMER (
                          customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name varchar(100) not null ,
                          email varchar(100) not null ,
                          mobile_number varchar(100) not null ,
                          created_at date not null ,
                          created_by varchar(100) not null ,
                          updated_at date default null ,
                          updated_by varchar(100) not null
);

CREATE TABLE accounts (
                          customer_id INT not null,
                          account_number INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          account_type varchar(100) not null ,
                          branch_address varchar(200) not null ,
                          created_at date not null ,
                          created_by varchar(100) not null ,
                          updated_at date default null ,
                          updated_by varchar(100) not null
);